### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by mrdschrute** [wmutschl/mutschler.dev#1]
On several (most?) pages, the "Why I (still) like btrfs" link points to https://mutschler.dev/btrfs/ and results in a 404 error. I think the working link is https://mutschler.dev/linux/btrfs/. I was going to do a pull request to fix the links on the pages, but it might be easier to add a redirect or move the btfs page to match the links.

Thanks for the guides!

**Comment by wmutschl** [comment]
Thanks for pointing this out! Fixed in 02253ade830dac05a064767ca1c2c798f3889375

**Comment by wmutschl** [comment]
I should probably re-write that post some time.
