### ISSUE TITLE
Pop!OS 22.04 Guide with BTRFS

### ISSUE THREAD

**Issue by u63725** [wmutschl/mutschler.dev#7]
Is it possible to backup Timeshift snapshots with btrfs to a remote target? Like btrfs send or btrbk to a network fileshare?

**Comment by wmutschl** [comment]
Sure, Timeshift snapshots are just btrfs snapshots, there is nothing special about them. So you can do a send/receive command on them manually. There are many tutorials for this, e.g. on the [Manjaro Forum](https://forum.manjaro.org/t/howto-use-btrfs-send-receive/135808).
